AWSTemplateFormatVersion: 2010-09-09
Description: IAM Eks for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  IamRoleEksCluster:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-eks-cluster
      Description: !Sub ${SystemName}-${EnvType}-iam-role-eks-cluster
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: eks.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-eks-cluster
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamRoleEksFargateProfile:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-eks-fargateprofile
      Description: !Sub ${SystemName}-${EnvType}-iam-role-eks-fargateprofile
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSFargatePodExecutionRolePolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: eks-fargate-pods.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-eks-fargateprofile
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  IamRoleEksClusterArn:
    Value: !GetAtt IamRoleEksCluster.Arn
    Export:
      Name: !Sub ${SystemName}-${EnvType}-iam-role-eks-cluster-arn
  IamRoleEksFargateProfileArn:
    Value: !GetAtt IamRoleEksFargateProfile.Arn
    Export:
      Name: !Sub ${SystemName}-${EnvType}-iam-role-eks-fargateprofile-arn
