AWSTemplateFormatVersion: 2010-09-09
Description: IAM Lambda for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  IamRoleLambdaHelloworld:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-lambda-helloworld
      Description: !Sub ${SystemName}-${EnvType}-iam-role-lambda-helloworld
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-lambda-helloworld
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyLambdaHelloworld:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref IamRoleLambdaHelloworld
      ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-lambda-helloworld
      Description: !Sub ${SystemName}-${EnvType}-iam-policy-lambda-helloworld
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - '*'
