AWSTemplateFormatVersion: '2010-09-09'
Description: Endpoint for Template

Parameters:
  SystemName:
    Type: String
    Default: xxxx
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3nd: ap-northeast-1d

Resources:
  # EndpointEcrDkr 作成
  EndpointEcrDkr:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.dkr
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-vpc
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - '*'
            Resource:
              - '*'
      SubnetIds:
        - Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-private-subnet1
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      SecurityGroupIds:
        - Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-endpoint-sg
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}

  # EndpointEcrApi 作成
  EndpointEcrApi:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ecr.api
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-vpc
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'
      SubnetIds:
        - Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-private-subnet1
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      SecurityGroupIds:
        - Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-endpoint-sg
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}

  # EndpointLogs 作成
  EndpointLogs:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.logs
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      VpcId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-vpc
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'
      SubnetIds:
        - Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-private-subnet1
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      SecurityGroupIds:
        - Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-endpoint-sg
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}

  # EndpointS3 作成
  EndpointS3:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcEndpointType: Gateway
      PrivateDnsEnabled: false
      VpcId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-vpc
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: '*'
            Resource: '*'
      RouteTableIds:
        - Fn::ImportValue: !Sub
            - ${SystemName}-${EnvType}-private-route-table1
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
