AWSTemplateFormatVersion: 2010-09-09
Description: SNS For Template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.
  isFifoTopic:
    Type: String
    AllowedValues: [true, false]
  EmailSubscriptionProtocol:
    Type: String
  EndpointEmailAddress:
    Type: String
  SMSSubscriptionProtocol:
    Type: String
  EndpointPhoneNumber:
    Type: String

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Conditions:
  HasEmailAddress: !Not [!Equals [!Ref EndpointEmailAddress, ""]]
  HasPhoneNumber: !Not [!Equals [!Ref EndpointPhoneNumber, ""]]

Resources:
  # SNSSubscription 作成
  # CodePipeline
  # Email
  SNSSubscriptionCodePipelineEmail:
    Condition: HasEmailAddress
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicCodePipeline
      Protocol: !Ref EmailSubscriptionProtocol
      Endpoint: !Ref EndpointEmailAddress
      Region: !Ref AWS::Region
  # SMS
  SNSSubscriptionCodePipelineSMS:
    Condition: HasPhoneNumber
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicCodePipeline
      Protocol: !Ref SMSSubscriptionProtocol
      Endpoint: !Ref EndpointPhoneNumber
      Region: !Ref AWS::Region
  # StepFunctions
  # Email
  SNSSubscriptionStepFunctionsEmail:
    Condition: HasEmailAddress
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicStepFunctions
      Protocol: !Ref EmailSubscriptionProtocol
      Endpoint: !Ref EndpointEmailAddress
      Region: !Ref AWS::Region
  # SMS
  SNSSubscriptionStepFunctionsSMS:
    Condition: HasPhoneNumber
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref SNSTopicStepFunctions
      Protocol: !Ref SMSSubscriptionProtocol
      Endpoint: !Ref EndpointPhoneNumber
      Region: !Ref AWS::Region

  # SNSTopicPolicy 作成
  # CodePipeline
  SNSTopicPolicyCodePipeline:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: CodeNotification_publish
            Effect: Allow
            Principal:
              Service:
                - codestar-notifications.amazonaws.com
            Action: sns:Publish
            Resource:
              - !Ref SNSTopicCodePipeline
      Topics:
        - !Ref SNSTopicCodePipeline
  # StepFunctions
  SNSTopicPolicyStepFunctions:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Statement:
          - Sid: StepFunctionsError
            Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action: sns:Publish
            Resource:
              - !Ref SNSTopicStepFunctions
      Topics:
        - !Ref SNSTopicStepFunctions

  # SNSTopic 作成
  # CodePipeline
  SNSTopicCodePipeline:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub
        - ${SystemName}-${EnvType}-sns-topic-code-pipeline
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      DisplayName: !Sub
        - ${SystemName}-${EnvType}-sns-topic-code-pipeline
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      FifoTopic: !Ref isFifoTopic
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-sns-topic-code-pipeline
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
  # StepFunctions
  SNSTopicStepFunctions:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub
        - ${SystemName}-${EnvType}-sns-topic-step-functions
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      DisplayName: !Sub
        - ${SystemName}-${EnvType}-sns-topic-step-functions
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      FifoTopic: !Ref isFifoTopic
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-sns-topic-step-functions
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  # CodePipeline
  SNSTopicCodePipelineArn:
    Value: !Ref SNSTopicCodePipeline
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-sns-topic-code-pipeline-arn
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  # StepFunctions
  SNSTopicStepFunctionsArn:
    Value: !Ref SNSTopicStepFunctions
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-sns-topic-step-functions-arn
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}