AWSTemplateFormatVersion: 2010-09-09
Description: KeyPair for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  Cryptography:
    Type: String
    AllowedValues: [rsa, ed25519]
  PrivateKeyFormat:
    Type: String
    AllowedValues: [pem, ppk]

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: !Sub ${SystemName}-${EnvType}-keypair
      KeyType: !Ref Cryptography
      KeyFormat: !Ref PrivateKeyFormat
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-keypair
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
