AWSTemplateFormatVersion: 2010-09-09
Description: Lambda for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  helloworldImageTag:
    Type: String
  LambdaMemorySize:
    Type: Number

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  LambdaHelloworld:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${SystemName}-${EnvType}-lambda-helloworld
      Description: !Sub ${SystemName}-${EnvType}-lambda-helloworld
      PackageType: Image
      Code:
        ImageUri: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/helloworld:${groupmanagerImageTag}
      Architectures:
        - x86_64
      MemorySize: !Ref LambdaMemorySize
      Timeout: 900
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/${SystemName}-${EnvType}-iam-role-lambda-helloworld
      Environment:
        Variables:
          SYSTEM_NAME: !Ref SystemName
          ENV_TYPE: !Ref EnvType
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-lambda-helloworld
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
