AWSTemplateFormatVersion: 2010-09-09
Description: TransitGateway for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  AmazonSideAsn:
    Type: Number
  isDnsSupport:
    Type: String
    AllowedValues: [enable, disable]
  isVpnEcmpSupport:
    Type: String
    AllowedValues: [enable, disable]
  isDefaultRouteTableAssociation:
    Type: String
    AllowedValues: [enable, disable]
  isDefaultRouteTablePropagation:
    Type: String
    AllowedValues: [enable, disable]
  isMulticastSupport:
    Type: String
    AllowedValues: [enable, disable]
  isAutoAcceptSharedAttachments:
    Type: String
    AllowedValues: [enable, disable]
  TransitGatewayCidrBlock:
    Type: String
    AllowedPattern: ((\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/(22|23|24))|^$)

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Conditions:
  hasTransitGatewayCidrBlock: !Not [ !Equals [ !Ref TransitGatewayCidrBlock, '' ] ]

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: !Sub ${SystemName}-${EnvType}-transitgateway
      AmazonSideAsn: !Ref AmazonSideAsn
      DnsSupport: !Ref isDnsSupport
      VpnEcmpSupport: !Ref isVpnEcmpSupport
      DefaultRouteTableAssociation: !Ref isDefaultRouteTableAssociation
      DefaultRouteTablePropagation: !Ref isDefaultRouteTablePropagation
      MulticastSupport: !Ref isMulticastSupport
      AutoAcceptSharedAttachments: !Ref isAutoAcceptSharedAttachments
      TransitGatewayCidrBlocks: !If
        - hasTransitGatewayCidrBlock
        - - !Ref TransitGatewayCidrBlock
        - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-transitgateway
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  TransitGatewayId:
    Value: !Ref TransitGateway
    Export:
      Name: !Sub ${SystemName}-${EnvType}-transitgateway-id
