AWSTemplateFormatVersion: 2010-09-09
Description: IAM Code for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  IamRoleCodeBuild:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-codebuild
      Description: !Sub ${SystemName}-${EnvType}-iam-role-codebuild
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-codebuild
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyCodeBuild:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref IamRoleCodeBuild
      ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-codebuild
      Description: !Sub ${SystemName}-${EnvType}-iam-policy-codebuild
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - '*'
          - Sid: AllowEcr
            Effect: Allow
            Action:
              - ecr:DescribeImages
            Resource:
              - '*'
          - Sid: AllowLambda
            Effect: Allow
            Action:
              - lambda:UpdateFunctionCode
            Resource:
              - '*'
          - Sid: AllowS3
            Effect: Allow
            Action:
              - s3:GetObject
            Resource:
              - '*'

  IamRoleCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-codepipeline
      Description: !Sub ${SystemName}-${EnvType}-iam-role-codepipeline
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codepipeline.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-codepipeline
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyCodePipeline:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref IamRoleCodePipeline
      ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-codepipeline
      Description: !Sub ${SystemName}-${EnvType}-iam-policy-codepipeline
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCodeBuild
            Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Resource:
              - '*'
          - Sid: AllowEcr
            Effect: Allow
            Action:
              - ecr:DescribeImages
            Resource:
              - '*'
          - Sid: AllowS3
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource:
              - '*'

  IamRoleEventBridgeCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-eventbridge-codepipeline
      Description: !Sub ${SystemName}-${EnvType}-iam-role-eventbridge-codepipeline
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: events.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-eventbridge-codepipeline
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyEventBridgeCodePipeline:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref IamRoleEventBridgeCodePipeline
      ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-eventbridge-codepipeline
      Description: !Sub ${SystemName}-${EnvType}-iam-policy-eventbridge-codepipeline
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCodeBuild
            Effect: Allow
            Action:
              - codepipeline:StartPipelineExecution
            Resource:
              - '*'
