AWSTemplateFormatVersion: 2010-09-09
Description: IAM Code for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  IamRoleCodeBuild:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-codebuild
      Description: !Sub ${SystemName}-${EnvType}-iam-role-codebuild
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/amazonec2containerregistryreadonly
        - arn:aws:iam::aws:policy/amazons3fullaccess
        - arn:aws:iam::aws:policy/awskeymanagementservicepoweruser
        - arn:aws:iam::aws:policy/cloudwatchlogsfullaccess
        - arn:aws:iam::aws:policy/awslambda_fullaccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-codebuild
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamRoleCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-codepipeline
      Description: !Sub ${SystemName}-${EnvType}-iam-role-codepipeline
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/amazonec2containerregistryreadonly
        - arn:aws:iam::aws:policy/amazons3fullaccess
        - arn:aws:iam::aws:policy/awskeymanagementservicepoweruser
        - arn:aws:iam::aws:policy/cloudwatchlogsfullaccess
        - arn:aws:iam::aws:policy/awslambda_fullaccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codepipeline.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-codepipeline
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamRoleEventBridgeCodePipeline:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-eventbridge-codepipeline
      Description: !Sub ${SystemName}-${EnvType}-iam-role-eventbridge-codepipeline
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodePipeline_FullAccess
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: events.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-eventbridge-codepipeline
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  # IamPolicyEcsTaskExecution:
  #   Type: AWS::IAM::ManagedPolicy
  #   Properties:
  #     Roles:
  #       - !Ref IamRoleEcsTaskExecution
  #     ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-ecs-task-execution
  #     Description: !Sub ${SystemName}-${EnvType}-iam-policy-ecs-task-execution
  #     PolicyDocument:
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: AllowCloudWatchLogs
  #           Effect: Allow
  #           Action:
  #             - logs:CreateLogGroup
  #           Resource:
  #             - '*'
