AWSTemplateFormatVersion: 2010-09-09
Description: LaunchTemplate Windows for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  AmiId:
    Type: String
  InstanceType:
    Type: String
  KeyName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  VolumeSize:
    Type: Number
  VolumeType:
    Type: String
    AllowedValues: [gp2, gp3, io1, io2, sc1, standard, st1]
  Iops:
    Type: String
  isDeleteOnTermination:
    Type: String
    AllowedValues: [true, false]
  isEncrypted:
    Type: String
    AllowedValues: [true, false]
  Throughput:
    Type: String
  HostnameType:
    Type: String
    AllowedValues: [ip-name, resource-name]
  isEnableResourceNameDnsARecord:
    Type: String
    AllowedValues: [true, false]
  isEnableResourceNameDnsAAAARecord:
    Type: String
    AllowedValues: [true, false]
  AutoRecovery:
    Type: String
    AllowedValues: [default, disabled]
  InstanceInitiatedShutdownBehavior:
    Type: String
    AllowedValues: [stop, terminate]
  isHibernation:
    Type: String
    AllowedValues: [true, false]
  isDisableApiTermination:
    Type: String
    AllowedValues: [true, false]
  isDisableApiStop:
    Type: String
    AllowedValues: [true, false]
  isDetailedMonitoring:
    Type: String
    AllowedValues: [true, false]
  isEbsOptimized:
    Type: String
    AllowedValues: [true, false]
  CapacityReservationPreference:
    Type: String
    AllowedValues: [open, none]
  Tenancy:
    Type: String
    AllowedValues: [default, dedicated, host]
  isNitroEnclave:
    Type: String
    AllowedValues: [true, false]
  MetadataHttpEndpoint:
    Type: String
    AllowedValues: [enabled, disabled]
  MetadataHttpTokens:
    Type: String
    AllowedValues: [required, optional]
  InstanceMetadataTags:
    Type: String
    AllowedValues: [enabled, disabled]

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Conditions:
  isEncryptedTrue: !Equals [ !Ref isEncrypted, true ]

Resources:
  LaunchTemplateWindows:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${SystemName}-${EnvType}-launchtemplate-windows
      VersionDescription: Initial Version
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        NetworkInterfaces:
          - SubnetId: !Ref AWS::NoValue
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${SystemName}-${EnvType}-securitygroup-ec2-windows-id
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              SnapshotId: !Ref AWS::NoValue
              VolumeSize: !Ref VolumeSize
              VolumeType: !Ref VolumeType
              Iops: !Ref Iops
              DeleteOnTermination: !Ref isDeleteOnTermination
              Encrypted: !Ref isEncrypted
              KmsKeyId: !If
                - isEncryptedTrue
                - !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/${SystemName}-${EnvType}-kms-ebs
                - !Ref AWS::NoValue
              Throughput: !Ref Throughput
        IamInstanceProfile:
          Arn: !Sub arn:aws:iam::${AWS::AccountId}:instance-profile/${SystemName}-${EnvType}-iam-instanceprofile-windows
        PrivateDnsNameOptions:
          HostnameType: !Ref HostnameType
          EnableResourceNameDnsARecord: !Ref isEnableResourceNameDnsARecord
          EnableResourceNameDnsAAAARecord: !Ref isEnableResourceNameDnsAAAARecord
        MaintenanceOptions:
          AutoRecovery: !Ref AutoRecovery
        InstanceInitiatedShutdownBehavior: !Ref InstanceInitiatedShutdownBehavior
        HibernationOptions:
          Configured: !Ref isHibernation
        DisableApiTermination: !Ref isDisableApiTermination
        DisableApiStop: !Ref isDisableApiStop
        Monitoring:
          Enabled: !Ref isDetailedMonitoring
        ElasticGpuSpecifications: !Ref AWS::NoValue
        CreditSpecification:
          CpuCredits: !Ref AWS::NoValue
        EbsOptimized: !Ref isEbsOptimized
        CapacityReservationSpecification:
          CapacityReservationPreference: !Ref CapacityReservationPreference
        Placement:
          Tenancy: !Ref Tenancy
        EnclaveOptions:
          Enabled: !Ref isNitroEnclave
        MetadataOptions:
          HttpEndpoint: !Ref MetadataHttpEndpoint
          HttpTokens: !Ref MetadataHttpTokens
          InstanceMetadataTags: !Ref InstanceMetadataTags
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${SystemName}-${EnvType}-ec2-windows
              - Key: SystemName
                Value: !Ref SystemName
              - Key: EnvType
                Value: !Ref EnvType
        UserData:
          Fn::Base64: !Sub |
            Coming soon ...
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value: !Sub ${SystemName}-${EnvType}-launchtemplate-windows
            - Key: SystemName
              Value: !Ref SystemName
            - Key: EnvType
              Value: !Ref EnvType

Outputs:
  LaunchTemplateWindowsId:
    Value: !Ref LaunchTemplateWindows
    Export:
      Name: !Sub ${SystemName}-${EnvType}-launchtemplate-windows-id
