AWSTemplateFormatVersion: 2010-09-09
Description: IAM FlowLog for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  IamRoleVpcFlowLog:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-vpc-flowlog
      Description: !Sub ${SystemName}-${EnvType}-iam-role-vpc-flowlog
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: vpc-flow-logs.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-vpc-flowlog
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyVpcFlowLog:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !Ref IamRoleVpcFlowLog
      PolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-vpc-flowlog
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
            Resource:
              - '*'
