AWSTemplateFormatVersion: 2010-09-09
Description: IAM ECS for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  IamRoleEcsTaskExecution:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-ecs-task-execution
      Description: !Sub ${SystemName}-${EnvType}-iam-role-ecs-task-execution
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-ecs-task-execution
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyEcsTaskExecution:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref IamRoleEcsTaskExecution
      ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-ecs-task-execution
      Description: !Sub ${SystemName}-${EnvType}-iam-policy-ecs-task-execution
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudWatchLogs
            Effect: Allow
            Action:
              - logs:CreateLogGroup
            Resource:
              - '*'

  IamRoleEcsTaskBastion:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${SystemName}-${EnvType}-iam-role-ecs-task-bastion
      Description: !Sub ${SystemName}-${EnvType}-iam-role-ecs-task-bastion
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSecurityTokenService
            Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: ecs-tasks.amazonaws.com
      Tags:
        - Key: Name
          Value: !Sub ${SystemName}-${EnvType}-iam-role-ecs-task-bastion
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

  IamPolicyEcsTaskBastion:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Roles:
        - !Ref IamRoleEcsTaskBastion
      ManagedPolicyName: !Sub ${SystemName}-${EnvType}-iam-policy-ecs-task-bastion
      Description: !Sub ${SystemName}-${EnvType}-iam-policy-ecs-task-bastion
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowEc2
            Effect: Allow
            Action:
              - ec2:DescribeKeyPairs
            Resource:
              - '*'
          - Sid: AllowKms
            Effect: Allow
            Action:
              - kms:Decrypt
            Resource:
              - '*'
          - Sid: AllowRoute53
            Effect: Allow
            Action:
              - route53:ChangeResourceRecordSets
              - route53:ListHostedZones
              - route53:ListHostedZonesByName
              - route53:ListResourceRecordSets
            Resource:
              - '*'
          - Sid: AllowSystemsManager
            Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - '*'
