AWSTemplateFormatVersion: 2010-09-09
Description: Route53 HostZone for template

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  EnvType:
    Type: String
    AllowedPattern: '[a-z0-9-]*'
  ParentNakedDomain:
    Type: String
    AllowedPattern: '^([a-z0-9][a-z0-9-]{1,61}[a-z0-9]\.)+[a-z]{2,}$'

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  HostedZoneParentNakedDomain:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ParentNakedDomain
      HostedZoneConfig:
        Comment: Domain for Bastion
      HostedZoneTags:
        - Key: Name
          Value: !Ref ParentNakedDomain
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType
